server:
  servlet:
    context-path: /desafio   port: 8080
spring:
  datasource:
    url: jdbc:mysql://andreschonrock.com.br:3306/desafio?serverTimezone=America/Sao_Paulo
    username: desafio
    password: desafio
  jpa:
    show-sql: true
  jackson:
    time-zone:
      America/Sao_Paulo
    date-format: dd-MM-yyyy HH:mm:ss